trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git config --global user.email "sync-bot@example.com"
    git config --global user.name "Sync Bot"
    git remote add github $(githubOrgRepoUrl)
    git fetch github
    git push github HEAD:main --tags
  displayName: 'Sync with GitHub Organization Repository'
