// src/pages/index.tsx
import React from 'react';
import Head from 'next/head';
import type { NextPage } from 'next';
import Layout from '../components/Layout';
import Introduction from '../components/Introduction';
import GradientLine from '../components/GradientLine';
import ProductSection from '../components/ProductSection';
import AvalonFeatures from '../components/AvalonFeatures';
import Testimonials from '../components/Testimonials';


const Homepage: NextPage = () => {
  return (
    <>
      <Head>
      <title>AvalonCore - Bridging the Digital Divide with Interoperable Ecosystem Technology</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Introduction />
        <GradientLine />
        <AvalonFeatures />
        <ProductSection />
        <Testimonials />
      </Layout>
    </>
  );
};

export default Homepage;
