// src/pages/index.tsx
import React from 'react';
import Head from 'next/head';
import type { NextPage } from 'next';
import Layout from '../components/Layout';
import Introduction from '../components/Introduction';
import ProductSection from '../components/ProductSection';
import AvalonFeatures from '../components/AvalonFeatures';


const Homepage: NextPage = () => {
  return (
    <>
      <Head>
      <title>AvalonCore - Bridging the Digital Divide with Interoperable Ecosystem Technology</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Introduction />
        <AvalonFeatures />
        <ProductSection />
      </Layout>
    </>
  );
};

export default Homepage;
