# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Avalonworldone

on:
  push:
    branches:
      - my-feature-branch
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://avalon.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_aebf077ab7aa4071befbfe9825348bd8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_95c332d83a5242c2a4530630ab1d0d5b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: avalon.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aebf077ab7aa4071befbfe9825348bd8 }}/avalonzone:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Avalonworldone'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_feb61b53bf404a77b7f558f33f222174 }}
        images: 'avalon.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aebf077ab7aa4071befbfe9825348bd8 }}/avalonzone:${{ github.sha }}'