name: Sync with GitHub Organization Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Azure DevOps repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.email "sync-bot@mycompany.com"
          git config --global user.name "Sync Bot"

      - name: Add GitHub remote
        run: |
          git remote add github ${{ secrets.GITHUB_ORG_REPO_URL }}
          git fetch github

      - name: Push changes to GitHub organization repository
        run: |
          git checkout main
          git merge --allow-unrelated-histories github/main
          git push github main
